Offtrac: src/alloc.c File Reference
src/alloc.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <errno.h>
#include "init.h"
#include <stddef.h>
Functions
double *** alloc3d (int NZED, int NY, int NX)
float *** alloc3d_f (int NZED, int NY, int NX)
void free3d (double ***arr3d, int NZED)
void free3d_f (float ***arr3d, int NZED)
float ** alloc2d_f (int NY, int NX)
void free2d_f (float **arr2d, int NY)
Function Documentation
float** alloc2d_f (int NY, int NX)
Definition at line 105 of file alloc.c.
Referenced by read_clim(), and read_fields().
double*** alloc3d (int NZED, int NY, int NX)
Definition at line 18 of file alloc.c.
Referenced by alloc_arrays(), alloc_tracadv(), initialize(), and tracer().
float*** alloc3d_f (int NZED, int NY, int NX)
Definition at line 46 of file alloc.c.
Referenced by read_biotic_bc(), read_clim(), read_h(), read_restoring(), read_ts(), and read_uvw().
void free2d_f (float ** arr2d, int NY)
Definition at line 125 of file alloc.c.
Referenced by read_clim(), and read_fields().
void free3d (double *** arr3d, int NZED)
Definition at line 74 of file alloc.c.
Referenced by initialize(), and tracer().
void free3d_f (float *** arr3d, int NZED)
Definition at line 87 of file alloc.c.
Referenced by read_biotic_bc(), read_clim(), read_h(), read_restoring(), read_ts(), and read_uvw().