Offtrac: src/alloc_arrays.h File Reference
src/alloc_arrays.h File Reference
Functions
int alloc_arrays ()
int alloc_error (char *arr_name)
Function Documentation
int alloc_arrays ()
Definition at line 12 of file alloc_arrays.c.
References age, alloc3d(), ea, eb, handle_error(), mn_age, mn_cfc11, mn_cfc12, mn_ea, mn_eb, mn_h, mn_rml, mn_sf6, mn_u, mn_uhtm, mn_v, mn_vhtm, NXMEM, NYMEM, NZ, u, uhtm, v, and vhtm.
Referenced by main().
int alloc_error (char * arr_name)
Definition at line 425 of file alloc_arrays.c.
References quit().