Offtrac: src/par_IO.c File Reference
src/par_IO.c File Reference
#include <stdio.h>
#include "init.h"
#include <stdlib.h>
Defines
#define pe_here 0
Functions
void collect_double_fields (double *field_in, int offx, int offy)
void spread_double_fields (double field_out[][NYMEM])
void spread_double_vector (double vec[], int numpts)
size_t read_layer (double field_out[][NYMEM], FILE *file, int float_vals)
size_t write_layer (double field_in[], FILE *file, int float_vals)
void quit (int status)
Variables
double io_field_d [(NXTOT+1)*(NYTOT+1)]
Define Documentation
#define pe_here 0
Definition at line 95 of file par_IO.c.
Function Documentation
void collect_double_fields (double * field_in, int offx, int offy)
Definition at line 100 of file par_IO.c.
References io_field_d, MAXPROC, nx, NXMEM, NXTOT, ny, NYMEM, NYTOT, pe_here, X0, X0abs, X1, Y0, Y0abs, and Y1.
Referenced by write_field(), and write_layer().
void quit (int status)
Definition at line 368 of file par_IO.c.
Referenced by alloc_error(), handle_error(), initialize_sponge(), and set_up_sponge_field().
size_t read_layer (double field_out[][NYMEM], FILE * file, int float_vals)
Definition at line 254 of file par_IO.c.
References io_field_d, nx, NXTOT, ny, NYTOT, pe_here, spread_double_fields(), X0, X0abs, Y0, and Y0abs.
void spread_double_fields (double field_out[][NYMEM])
Definition at line 166 of file par_IO.c.
References io_field_d, nx, NXMEM, NXTOT, ny, NYTOT, pe_here, X0, X0abs, Y0, and Y0abs.
void spread_double_vector (double vec[], int numpts)
Definition at line 231 of file par_IO.c.
References io_field_d, and pe_here.
Referenced by read_field().
size_t write_layer (double field_in[], FILE * file, int float_vals)
Definition at line 310 of file par_IO.c.
References collect_double_fields(), io_field_d, nx, NXTOT, ny, NYMEM, NYTOT, pe_here, X0, X0abs, X1, Y0, Y0abs, and Y1.
Referenced by write_field().
Variable Documentation
double io_field_d[(NXTOT+1)*(NYTOT+1)]
Definition at line 39 of file iocdf.c.
Referenced by collect_double_fields(), read_layer(), spread_double_fields(), spread_double_vector(), write_field(), and write_layer().