Offtrac: src/read.c File Reference
src/read.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <errno.h>
#include "netcdf.h"
#include "init.h"
#include "io.h"
#include "iocdf.h"
#include "alloc.h"
#include "read.h"
#include "step.h"
#include "util.h"
#include "metrics.h"
Defines
#define ERR(e) {printf("Error: %s\n", nc_strerror(e)); exit(2);}
Functions
void read_fields (int imon, int itts)
void read_fieldave (int imon)
void read_grid ()
void read_D ()
void read_clim (int imon, int inxt, int ilst)
void read_uvw (int imon, int itts)
void read_h (int imon, int inxt)
void read_biotic_bc (int imon, int itts)
void read_ts (int imon, int itts)
void read_tracer_init (int imon)
void read_restoring (int imon, int itts)
void read_buoy (int imon)
int read_trac (double sc_coeffs[4], double sol_coeffs[7], int tracyear[MAXRECS], double Ncon[MAXRECS], double Scon[MAXRECS])
Variables
const double misval
double areagr [NXMEM][NYMEM]
double *** u
double *** v
double h [NZ][NXMEM][NYMEM]
double hend [NZ][NXMEM][NYMEM]
double hstart [NZ][NXMEM][NYMEM]
double rml [2][NXMEM][NYMEM]
double po4_star_lev [NZPHOS][NXMEM][NYMEM]
double po4_star_lay [NZ][NXMEM][NYMEM]
double salt_woa [NXMEM][NYMEM]
double dt
int beginyear
int theyear
int lastsave
double *** uhtm
double *** vhtm
double *** ea
double *** eb
double eaml [NXMEM][NYMEM]
double Temptm [NZ][NXMEM][NYMEM]
double Salttm [NZ][NXMEM][NYMEM]
double atmpres [NXMEM][NYMEM]
double xkw [NXMEM][NYMEM]
double fice [NXMEM][NYMEM]
double wd [NZ+1][NXMEM][NYMEM]
double D [NXMEM][NYMEM]
char directory [75]
char inittrac [200]
double qlat [NYMEM]
double hlat [NYMEM]
double age_init [NZ][NXMEM][NYMEM]
double cfc11_init [NZ][NXMEM][NYMEM]
double cfc12_init [NZ][NXMEM][NYMEM]
double sf6_init [NZ][NXMEM][NYMEM]
Define Documentation
#define ERR (e) {printf("Error: %s\n", nc_strerror(e)); exit(2);}
Definition at line 179 of file read.c.
Referenced by read_biotic_bc(), read_clim(), read_fields(), read_h(), read_restoring(), read_ts(), and read_uvw().
Function Documentation
void read_biotic_bc (int imon, int itts)
Definition at line 1309 of file read.c.
References alloc3d_f(), close_file(), directory, ERR, free3d_f(), ii, NTSTEP, nx, NXTOT, ny, NYMEM, NYTOT, NZPHOS, open_input_file(), and po4_star_lev.
Referenced by main(), and read_tracer_init().
void read_buoy (int imon)
Definition at line 2753 of file read.c.
void read_clim (int imon, int inxt, int ilst)
Definition at line 585 of file read.c.
References alloc2d_f(), alloc3d_f(), close_file(), directory, dt, ERR, free2d_f(), free3d_f(), h, hend, ii, nx, NXTOT, ny, NYMEM, NYTOT, NZ, open_input_file(), uhtm, vhtm, and wd.
Referenced by main().
void read_D ()
Definition at line 538 of file read.c.
References close_file(), D, directory, ii, nx, NXTOT, ny, NYMEM, NYTOT, open_input_file(), read_field(), X1, and Y1.
Referenced by main().
void read_fieldave (int imon)
Definition at line 313 of file read.c.
void read_fields (int imon, int itts)
Definition at line 182 of file read.c.
References alloc2d_f(), atmpres, close_file(), directory, ERR, fice, free2d_f(), NTSTEP, NXMEM, NXTOT, NYTOT, open_input_file(), and xkw.
Referenced by main().
void read_grid ()
Definition at line 317 of file read.c.
References areagr, close_file(), directory, DXh, DXq, DXu, DXv, DYh, DYq, DYu, DYv, handle_error(), hlat, ii, lath, latq, nx, NXTOT, ny, NYMEM, NYTOT, open_input_file(), and qlat.
Referenced by main().
void read_h (int imon, int inxt)
Definition at line 1124 of file read.c.
References alloc3d_f(), close_file(), directory, ERR, free3d_f(), h, hend, hstart, ii, nx, NXTOT, ny, NYMEM, NYTOT, NZ, and open_input_file().
Referenced by main().
void read_restoring (int imon, int itts)
Definition at line 2565 of file read.c.
References alloc3d_f(), close_file(), conc_obs_layer(), directory, ERR, free3d_f(), h, NTSTEP, NYMEM, NYTOT, and open_input_file().
Referenced by main().
int read_trac (double sc_coeffs[4], double sol_coeffs[7], int tracyear[MAXRECS], double Ncon[MAXRECS], double Scon[MAXRECS])
Definition at line 2840 of file read.c.
References fname.
Referenced by main().
void read_tracer_init (int imon)
Definition at line 2290 of file read.c.
References age_init, cfc11_init, cfc12_init, conc_obs_layer(), D, h, MINIMUM_DEPTH, misval, NYMEM, NYTOT, open_input_file(), po4_star_lay, po4_star_lev, read_biotic_bc(), read_field(), rflags, set_darray3d_zero(), set_fix_darray3d_zero(), sf6_init, X1, and Y1.
Referenced by initialize().
void read_ts (int imon, int itts)
Definition at line 1942 of file read.c.
References alloc3d_f(), close_file(), directory, ERR, free3d_f(), NTSTEP, NYTOT, open_input_file(), salt_woa, Salttm, and Temptm.
Referenced by main().
void read_uvw (int imon, int itts)
Definition at line 744 of file read.c.
References alloc3d_f(), close_file(), directory, dt, ERR, free3d_f(), NMONTHS, NTSTEP, NXTOT, NYTOT, NZ, open_input_file(), uhtm, vhtm, and wd.
Referenced by main().
Variable Documentation
double age_init[NZ][NXMEM][NYMEM]
Definition at line 227 of file offtrac.c.
double areagr[NXMEM][NYMEM]
Definition at line 181 of file offtrac.c.
Referenced by read_grid(), and set_metrics().
double atmpres[NXMEM][NYMEM]
Definition at line 179 of file offtrac.c.
int beginyear
Definition at line 207 of file offtrac.c.
double cfc11_init[NZ][NXMEM][NYMEM]
Definition at line 270 of file offtrac.c.
double cfc12_init[NZ][NXMEM][NYMEM]
Definition at line 271 of file offtrac.c.
double D[NXMEM][NYMEM]
Definition at line 182 of file offtrac.c.
char directory[75]
Definition at line 493 of file offtrac.c.
Referenced by main(), read_biotic_bc(), read_clim(), read_D(), read_fields(), read_grid(), read_h(), read_restoring(), read_ts(), and read_uvw().
double dt
Definition at line 485 of file offtrac.c.
double*** ea
Definition at line 163 of file offtrac.c.
double eaml[NXMEM][NYMEM]
Definition at line 165 of file offtrac.c.
double *** eb
Definition at line 164 of file offtrac.c.
double fice[NXMEM][NYMEM]
Definition at line 178 of file offtrac.c.
double h[NZ][NXMEM][NYMEM]
Definition at line 143 of file offtrac.c.
double hend[NZ][NXMEM][NYMEM]
Definition at line 144 of file offtrac.c.
double hlat[NYMEM]
Definition at line 199 of file offtrac.c.
double hstart[NZ][NXMEM][NYMEM]
Definition at line 148 of file offtrac.c.
char inittrac[200]
Definition at line 495 of file offtrac.c.
int lastsave
Definition at line 209 of file offtrac.c.
const double misval
Definition at line 48 of file offtrac.c.
double po4_star_lay[NZ][NXMEM][NYMEM]
Referenced by main(), read_tracer_init(), and step_fields().
double po4_star_lev[NZPHOS][NXMEM][NYMEM]
Referenced by read_biotic_bc(), read_tracer_init(), and step_fields().
double qlat[NYMEM]
Definition at line 198 of file offtrac.c.
double rml[2][NXMEM][NYMEM]
Definition at line 155 of file offtrac.c.
double salt_woa[NXMEM][NYMEM]
Definition at line 175 of file offtrac.c.
double Salttm[NZ][NXMEM][NYMEM]
Definition at line 174 of file offtrac.c.
double sf6_init[NZ][NXMEM][NYMEM]
Definition at line 309 of file offtrac.c.
double Temptm[NZ][NXMEM][NYMEM]
Definition at line 173 of file offtrac.c.
int theyear
Definition at line 208 of file offtrac.c.
double*** u
Definition at line 141 of file offtrac.c.
double*** uhtm
Definition at line 161 of file offtrac.c.
double*** v
Definition at line 142 of file offtrac.c.
double *** vhtm
Definition at line 162 of file offtrac.c.
double wd[NZ+1][NXMEM][NYMEM]
Definition at line 171 of file offtrac.c.
double xkw[NXMEM][NYMEM]
Definition at line 177 of file offtrac.c.