Offtrac: src/read.h File Reference
src/read.h File Reference
Functions
void read_fieldave (int imon)
void read_D ()
void read_uvw (int imon, int itts)
void read_h (int imon, int inxt)
void read_fields (int imon, int itts)
void read_biotic_bc (int imon, int itts)
void read_ts (int imon, int itts)
void read_clim (int imon, int inxt, int ilst)
void read_tracer_init (int imon)
void read_buoy (int imon)
void read_sponge (void)
void read_grid ()
int read_trac (double sc_coeffs[4], double sol_coeffs[7], int tracyear[MAXRECS], double Ncon[MAXRECS], double Scon[MAXRECS])
Function Documentation
void read_biotic_bc (int imon, int itts)
Definition at line 1309 of file read.c.
References alloc3d_f(), close_file(), directory, ERR, free3d_f(), ii, NTSTEP, nx, NXTOT, ny, NYMEM, NYTOT, NZPHOS, open_input_file(), and po4_star_lev.
Referenced by main(), and read_tracer_init().
void read_buoy (int imon)
Definition at line 2753 of file read.c.
void read_clim (int imon, int inxt, int ilst)
Definition at line 585 of file read.c.
References alloc2d_f(), alloc3d_f(), close_file(), directory, dt, ERR, free2d_f(), free3d_f(), h, hend, ii, nx, NXTOT, ny, NYMEM, NYTOT, NZ, open_input_file(), uhtm, vhtm, and wd.
Referenced by main().
void read_D ()
Definition at line 538 of file read.c.
References close_file(), D, directory, ii, nx, NXTOT, ny, NYMEM, NYTOT, open_input_file(), read_field(), X1, and Y1.
Referenced by main().
void read_fieldave (int imon)
Definition at line 313 of file read.c.
void read_fields (int imon, int itts)
Definition at line 182 of file read.c.
References alloc2d_f(), atmpres, close_file(), directory, ERR, fice, free2d_f(), NTSTEP, NXMEM, NXTOT, NYTOT, open_input_file(), and xkw.
Referenced by main().
void read_grid ()
Definition at line 317 of file read.c.
References areagr, close_file(), directory, DXh, DXq, DXu, DXv, DYh, DYq, DYu, DYv, handle_error(), hlat, ii, lath, latq, nx, NXTOT, ny, NYMEM, NYTOT, open_input_file(), and qlat.
Referenced by main().
void read_h (int imon, int inxt)
Definition at line 1124 of file read.c.
References alloc3d_f(), close_file(), directory, ERR, free3d_f(), h, hend, hstart, ii, nx, NXTOT, ny, NYMEM, NYTOT, NZ, and open_input_file().
Referenced by main().
void read_sponge (void)
Referenced by initialize().
int read_trac (double sc_coeffs[4], double sol_coeffs[7], int tracyear[MAXRECS], double Ncon[MAXRECS], double Scon[MAXRECS])
Definition at line 2840 of file read.c.
References fname.
Referenced by main().
void read_tracer_init (int imon)
Definition at line 2290 of file read.c.
References age_init, cfc11_init, cfc12_init, conc_obs_layer(), D, h, MINIMUM_DEPTH, misval, NYMEM, NYTOT, open_input_file(), po4_star_lay, po4_star_lev, read_biotic_bc(), read_field(), rflags, set_darray3d_zero(), set_fix_darray3d_zero(), sf6_init, X1, and Y1.
Referenced by initialize().
void read_ts (int imon, int itts)
Definition at line 1942 of file read.c.
References alloc3d_f(), close_file(), directory, ERR, free3d_f(), NTSTEP, NYTOT, open_input_file(), salt_woa, Salttm, and Temptm.
Referenced by main().
void read_uvw (int imon, int itts)
Definition at line 744 of file read.c.
References alloc3d_f(), close_file(), directory, dt, ERR, free3d_f(), NMONTHS, NTSTEP, NXTOT, NYTOT, NZ, open_input_file(), uhtm, vhtm, and wd.
Referenced by main().