Offtrac: src/step.h File Reference
src/step.h File Reference
Functions
double lin_interp (double pleth, const double x[], const double z[], int istart, int npts)
double lin_interpp (double pleth, const double x[], const double z[], int istart, int npts)
void conc_obs_layer (double h[NZ][NXMEM][NYMEM], double conc_lev[NZPHOS][NXMEM][NYMEM], double conc_lay[NZ][NXMEM][NYMEM])
void z_depth (double h[NZ][NXMEM][NYMEM], double depth[NZ][NXMEM][NYMEM])
double trac_calcsol (double TempK, double S, double sol_coeffs[7])
double trac_atmospheric (int iteryear, double iteryearfrac, int tracrecs, int tracyear[MAXRECS], double tracN[MAXRECS], double tracS[MAXRECS], int latidx)
double trac_schmidt (double T, double sc_coeffs[4])
double trac_calcflux (double trac_Sc, double trac_atm, double trac_sol, double icefrac, double pistonvel, double pres, double trac_con, double dt)
Function Documentation
void conc_obs_layer (double h[NZ][NXMEM][NYMEM], double conc_lev[NZPHOS][NXMEM][NYMEM], double conc_lay[NZ][NXMEM][NYMEM])
Definition at line 1616 of file step.c.
References D, depth, h, lin_interp(), MINIMUM_DEPTH, misval, NXMEM, NZ, NZPHOS, and z_depth().
Referenced by read_restoring(), read_tracer_init(), and step_fields().
double lin_interp (double pleth, const double x[], const double z[], int istart, int npts)
Definition at line 1535 of file step.c.
Referenced by conc_obs_layer().
double lin_interpp (double pleth, const double x[], const double z[], int istart, int npts)
Referenced by initialize().
double trac_atmospheric (int iteryear, double iteryearfrac, int tracrecs, int tracyear[MAXRECS], double tracN[MAXRECS], double tracS[MAXRECS], int latidx)
Definition at line 2739 of file step.c.
References BEGHIND, lath, linear_interp(), NXTOT, and SPINUP.
Referenced by step_fields().
double trac_calcflux (double trac_Sc, double trac_atm, double trac_sol, double icefrac, double pistonvel, double pres, double trac_con, double dt)
Definition at line 2792 of file step.c.
References h_mixedlyr.
Referenced by step_fields().
double trac_calcsol (double TempK, double S, double sol_coeffs[7])
Definition at line 2726 of file step.c.
Referenced by step_fields().
double trac_schmidt (double T, double sc_coeffs[4])
Definition at line 2786 of file step.c.
Referenced by step_fields().
void z_depth (double h[NZ][NXMEM][NYMEM], double depth[NZ][NXMEM][NYMEM])
Definition at line 1480 of file step.c.
References D, depth, h, MINIMUM_DEPTH, misval, nx, ny, NZ, X1, and Y1.
Referenced by conc_obs_layer(), initialize(), and step_fields().