Offtrac: src/io.h File Reference
src/io.h File Reference
#include <stddef.h>
Data Structures
struct vardesc
struct varcdfinfo
Defines
#define DOUBLE_FILE 0
#define FLOAT_FILE 1
#define NETCDF_FILE 2
Functions
size_t write_field (int cdfid, FILE *fileptr, struct vardesc vars, struct varcdfinfo varinfo, size_t nrec, double *variable)
void create_file (char filename[], int type, struct vardesc vars[], int novars, FILE **fileptr, int *cdfid, int *timeid, struct varcdfinfo varinfo[], int output_prec_float)
int name_output_file (char name[], double day, int noexdig, char filepath[], char directory[])
size_t write_time (int cdfid, FILE *fileptr, int timeid, size_t nrec, double *day)
size_t read_time (int cdfid, FILE *fileptr, int timeid, size_t nrec, double *day)
void close_file (int *cdfid, FILE **fileptr)
void find_input_file (char name[], char name2[], char fltname[], double day, char directory[], FILE **file, int *cdfid, int *timeid)
int open_input_file (char filename[], FILE **fileptr, int *cdfid, int *timeid)
void read_field (int cdfid, FILE *fileptr, char varname[], int size_x, int size_y, int size_z, int start_file_x, int start_file_y, int start_file_z, int start_array_x, int start_array_y, int start_array_z, int recno, double variable[])
double *** alloc3d (int NZED, int NY, int NX)
Define Documentation
#define DOUBLE_FILE 0
Definition at line 6 of file io.h.
#define FLOAT_FILE 1
Definition at line 7 of file io.h.
Referenced by create_file(), and name_output_file().
#define NETCDF_FILE 2
Definition at line 8 of file io.h.
Referenced by create_file(), main(), and name_output_file().
Function Documentation
double*** alloc3d (int NZED, int NY, int NX)
Definition at line 18 of file alloc.c.
Referenced by alloc_arrays(), alloc_tracadv(), initialize(), and tracer().
void close_file (int * cdfid, FILE ** fileptr)
Definition at line 736 of file iocdf.c.
References handle_error().
Referenced by main(), read_biotic_bc(), read_clim(), read_D(), read_fields(), read_grid(), read_h(), read_restoring(), read_ts(), and read_uvw().
void create_file (char filename[], int type, struct vardesc vars[], int novars, FILE ** fileptr, int * cdfid, int * timeid, struct varcdfinfo varinfo[], int output_prec_float)
Definition at line 232 of file iocdf.c.
References varcdfinfo::count, FLOAT_FILE, handle_error(), junk, KD, KDML, KHTR, lath, latq, lonh, lonq, NETCDF_FILE, nx, NXTOT, ny, NYTOT, NZ, pe_here, r_bio_tau, X0, X0abs, X1, varcdfinfo::x_size, Y0, Y0abs, Y1, varcdfinfo::y_size, and varcdfinfo::z_size.
Referenced by main().
void find_input_file (char name[], char name2[], char fltname[], double day, char directory[], FILE ** file, int * cdfid, int * timeid)
Definition at line 831 of file iocdf.c.
References NXTOT, NYTOT, and open_input_file().
int name_output_file (char name[], double day, int noexdig, char filepath[], char directory[])
Definition at line 764 of file iocdf.c.
References FLOAT_FILE, NETCDF_FILE, NXTOT, NYTOT, and SAVEINT.
int open_input_file (char filename[], FILE ** fileptr, int * cdfid, int * timeid)
Definition at line 897 of file iocdf.c.
References pe_here.
Referenced by find_input_file(), read_biotic_bc(), read_clim(), read_D(), read_fields(), read_grid(), read_h(), read_restoring(), read_tracer_init(), read_ts(), and read_uvw().
void read_field (int cdfid, FILE * fileptr, char varname[], int size_x, int size_y, int size_z, int start_file_x, int start_file_y, int start_file_z, int start_array_x, int start_array_y, int start_array_z, int recno, double variable[])
Definition at line 960 of file iocdf.c.
References handle_error(), nx, NXMEM, NXTOT, ny, NYMEM, NYTOT, NZ, pe_here, read_layer(), spread_double_vector(), X0, X0abs, Y0, and Y0abs.
Referenced by read_D(), and read_tracer_init().
size_t read_time (int cdfid, FILE * fileptr, int timeid, size_t nrec, double * day)
Definition at line 1139 of file iocdf.c.
References handle_error(), and pe_here.
size_t write_field (int cdfid, FILE * fileptr, struct vardesc vars, struct varcdfinfo varinfo, size_t nrec, double * variable)
Definition at line 78 of file iocdf.c.
References collect_double_fields(), varcdfinfo::count, handle_error(), vardesc::hor_grid, varcdfinfo::id, io_field_d, vardesc::name, nx, NXMEM, NXTOT, ny, NYMEM, NYTOT, NZ, pe_here, vardesc::t_grid, write_layer(), varcdfinfo::x_size, varcdfinfo::y_size, vardesc::z_grid, and varcdfinfo::z_size.
Referenced by main().
size_t write_time (int cdfid, FILE * fileptr, int timeid, size_t nrec, double * day)
Definition at line 210 of file iocdf.c.
References handle_error(), and pe_here.
Referenced by main().