Offtrac: src/iocdf.h File Reference
src/iocdf.h File Reference
Functions
void handle_error (char message[], int status)
Function Documentation
void handle_error (char message[], int status)
Definition at line 755 of file iocdf.c.
References pe_here, and quit().
Referenced by alloc_arrays(), close_file(), create_file(), main(), read_field(), read_grid(), read_time(), write_field(), and write_time().