Offtrac: src/offtrac.h File Reference
src/offtrac.h File Reference
#include <stddef.h>
#include <stdio.h>
Data Structures
struct params
Defines
#define TO_NORTH 1
#define TO_SOUTH 2
#define TO_EAST 4
#define TO_WEST 8
Functions
void alloc_fields (void)
void tracer (int itts)
void initialize (int imon)
void collect_double_fields (double *field_in, int offx, int offy)
void spread_double_fields (double field_out[NXMEM][NYMEM])
void spread_double_vector (double vec[], int numpts)
size_t write_layer (double field_in[], FILE *file, int float_vals)
size_t read_layer (double field_out[NXMEM][NYMEM], FILE *file, int float_vals)
void set_metrics (void)
void initializemasks (void)
void set_up_parallel (void)
void pass_vars (double var[][NXMEM][NYMEM], int nz, int pts_out, int nrows, double bounds, int dosync, int safemem, int dirflag)
void pass_var_2d (double var[NXMEM][NYMEM], int nz, int pts_out, int nrows, double bounds, int dosync, int safemem, int dirflag)
void spread_string (char name[], int length)
void sum_fields (double vec[], int numsum)
void sum_int_fields (int vec[], int numsum)
void check_field (double field_in[NXMEM][NYMEM], char write_string[], int i0, int i1, int j0, int j1)
void quit (int status)
Define Documentation
#define TO_EAST 4
Definition at line 123 of file offtrac.h.
#define TO_NORTH 1
Definition at line 121 of file offtrac.h.
#define TO_SOUTH 2
Definition at line 122 of file offtrac.h.
#define TO_WEST 8
Definition at line 124 of file offtrac.h.
Function Documentation
void alloc_fields (void)
Definition at line 2449 of file offtrac.c.
References D, flags, junk, mn_age, mn_c11flux, mn_c12flux, mn_cfc11, mn_cfc12, mn_ea, mn_eaml, mn_eb, mn_h, mn_rml, mn_sf6, mn_sf6flux, mn_u, mn_uhtm, mn_v, mn_vhtm, Temptm, var, and varsize.
Referenced by main().
void check_field (double field_in[NXMEM][NYMEM], char write_string[], int i0, int i1, int j0, int j1)
void collect_double_fields (double * field_in, int offx, int offy)
Definition at line 100 of file par_IO.c.
References io_field_d, MAXPROC, nx, NXMEM, NXTOT, ny, NYMEM, NYTOT, pe_here, X0, X0abs, X1, Y0, Y0abs, and Y1.
Referenced by write_field(), and write_layer().
void initialize (int imon)
Definition at line 183 of file initialize.c.
References age, age_init, alloc3d(), cfc11, cfc11_init, cfc12, cfc12_init, D, depth, free3d(), h, hstart, initialize_sponge(), initializemasks(), lath, lin_interpp(), mAGE, mCFC11, mCFC12, merge_ml_tr(), MINIMUM_DEPTH, misval, mSF6, NTR, nx, NXMEM, ny, NYMEM, NZ, read_sponge(), read_tracer_init(), set_up_sponge_field(), sf6, sf6_init, tr, u, uhtm, v, vhtm, X1, Y1, and z_depth().
Referenced by main().
void initializemasks (void)
Definition at line 13 of file masks.c.
References D, EPSILON, MINIMUM_DEPTH, nx, ny, umask, vmask, X0, and Y0.
void pass_var_2d (double var[NXMEM][NYMEM], int nz, int pts_out, int nrows, double bounds, int dosync, int safemem, int dirflag)
void pass_vars (double var[][NXMEM][NYMEM], int nz, int pts_out, int nrows, double bounds, int dosync, int safemem, int dirflag)
void quit (int status)
Definition at line 368 of file par_IO.c.
size_t read_layer (double field_out[NXMEM][NYMEM], FILE * file, int float_vals)
Referenced by read_field().
void set_metrics (void)
Definition at line 86 of file set_metrics.c.
References areagr, D, DXDYh, DXDYq, DXh, DXq, DXu, DXv, DYh, DYq, DYu, DYv, hlat, IDXDYh, IDXDYq, IDXh, IDXq, IDXu, IDXv, IDYh, IDYq, IDYu, IDYv, lath, latq, LENLAT, LENLON, lonh, lonq, LOWLAT, nx, NXMEM, NXTOT, ny, NYMEM, NYTOT, qlat, RE, WESTLON, X0, X0abs, Y0, and Y0abs.
void set_up_parallel (void)
void spread_double_fields (double field_out[NXMEM][NYMEM])
Referenced by read_layer().
void spread_double_vector (double vec[], int numpts)
Definition at line 231 of file par_IO.c.
Referenced by read_field().
void spread_string (char name[], int length)
void sum_fields (double vec[], int numsum)
void sum_int_fields (int vec[], int numsum)
void tracer (int itts)
Definition at line 98 of file tracadv.c.
References alloc3d(), D_MAX, D_MIN, DT, dt, DXDYh, DXv, DYu, ea, eaml, eb, EPSILON, free3d(), h, hend, HMIX, hstart, IDXDYh, IDXu, IDYv, ii, KD, KDML, KHTR, NTR, NTSTEP, NUM_ADV_ITER, nx, NXMEM, ny, NYMEM, NZ, print_tr(), pstage, tr, uhtm, umask, vhtm, vmask, wd, X0, X1, Y0, and Y1.
Referenced by step_fields().
size_t write_layer (double field_in[], FILE * file, int float_vals)
Definition at line 310 of file par_IO.c.
Referenced by write_field().