Offtrac: src/sponge.c File Reference
src/sponge.c File Reference
#include <stdlib.h>
#include <math.h>
#include <stdio.h>
#include "init.h"
#include "par_IO.h"
Defines
#define NOFLD (NTR+1)
#define D_MIN(a, b)
#define D_MAX(a, b)
Functions
void initialize_sponge (double Iresttime[NXMEM][NYMEM], int num_fields)
void set_up_sponge_field (double sp_val[][NXMEM][NYMEM], double(*f_ptr)[][NXMEM][NYMEM], int nlay)
void apply_sponge (double h[NZ][NXMEM][NYMEM], double dt, double ea[NZ][NXMEM][NYMEM], double eb[NZ][NXMEM][NYMEM])
Variables
double D [NXMEM][NYMEM]
double **** tr
Define Documentation
#define D_MAX (a, b)
Value:
(dmina1=(a),dmina2=(b),((dmina1) > (dmina2)) ?\
                    (dmina1) : (dmina2))
Definition at line 13 of file sponge.c.
Referenced by tracer().
#define D_MIN (a, b)
Value:
(dmina1=(a),dmina2=(b),((dmina1) < (dmina2)) ?\
                    (dmina1) : (dmina2))
Definition at line 11 of file sponge.c.
Referenced by apply_sponge(), and tracer().
#define NOFLD (NTR+1)
Definition at line 8 of file sponge.c.
Referenced by initialize_sponge().
Function Documentation
void apply_sponge (double h[NZ][NXMEM][NYMEM], double dt, double ea[NZ][NXMEM][NYMEM], double eb[NZ][NXMEM][NYMEM])
Definition at line 138 of file sponge.c.
References D, D_MIN, EPSILON, h, NZ, tr, and var.
Referenced by step_fields().
void initialize_sponge (double Iresttime[NXMEM][NYMEM], int num_fields)
Definition at line 40 of file sponge.c.
References D, MINIMUM_DEPTH, NOFLD, nx, ny, NZ, quit(), X1, and Y1.
void set_up_sponge_field (double sp_val[][NXMEM][NYMEM], double(*) f_ptr[][NXMEM][NYMEM], int nlay)
Definition at line 99 of file sponge.c.
References NZ, quit(), and var.
Referenced by initialize().
Variable Documentation
double D[NXMEM][NYMEM]
Definition at line 182 of file offtrac.c.
double**** tr
Definition at line 183 of file offtrac.c.