Offtrac: src/util.c File Reference
src/util.c File Reference
#include "init.h"
Functions
void set_darray2d_zero (double **arr, int NX, int NY)
void set_darray3d_zero (double ***arr, int nz, int NX, int NY)
void set_fix_darray3d_zero (double arr[][NXMEM][NYMEM], int nz)
void set_fix_darray2d_zero (double arr[NXMEM][NYMEM])
void add_fix_darray2d (double arr1[NXMEM][NYMEM], double arr2[NXMEM][NYMEM])
void mult_fix_darray2d (double arr[NXMEM][NYMEM], double factor)
void add_darray3d (double ***arr1, double ***arr2, int nz, int NX, int NY)
void mult_darray3d (double ***arr, int nz, int NX, int NY, double factor)
void mult_fix_darray2d_mv (double arr[NXMEM][NYMEM], double factor, double D[NXMEM][NYMEM], double mv)
void mult_darray3d_mv (double ***arr, int nz, int NX, int NY, double factor, double D[NXMEM][NYMEM], double mv)
void copy_darray3d (double ***arr1, double ***arr2, int nz, int NX, int NY)
void copy_fix_darray3d (double ***arr1, double arr2[NZ][NXMEM][NYMEM], int nz, int NX, int NY)
double linear_interp (double x0, double y0, double x1, double y1, double xstar)
Function Documentation
void add_darray3d (double *** arr1, double *** arr2, int nz, int NX, int NY)
Definition at line 48 of file util.c.
Referenced by main().
void add_fix_darray2d (double arr1[NXMEM][NYMEM], double arr2[NXMEM][NYMEM])
Definition at line 34 of file util.c.
References NXMEM.
Referenced by main().
void copy_darray3d (double *** arr1, double *** arr2, int nz, int NX, int NY)
Definition at line 98 of file util.c.
Referenced by main().
void copy_fix_darray3d (double *** arr1, double arr2[NZ][NXMEM][NYMEM], int nz, int NX, int NY)
Definition at line 106 of file util.c.
Referenced by main().
double linear_interp (double x0, double y0, double x1, double y1, double xstar)
Definition at line 116 of file util.c.
Referenced by trac_atmospheric().
void mult_darray3d (double *** arr, int nz, int NX, int NY, double factor)
Definition at line 56 of file util.c.
Referenced by main().
void mult_darray3d_mv (double *** arr, int nz, int NX, int NY, double factor, double D[NXMEM][NYMEM], double mv)
Definition at line 76 of file util.c.
References D, and MINIMUM_DEPTH.
Referenced by main().
void mult_fix_darray2d (double arr[NXMEM][NYMEM], double factor)
Definition at line 41 of file util.c.
References NXMEM.
Referenced by main().
void mult_fix_darray2d_mv (double arr[NXMEM][NYMEM], double factor, double D[NXMEM][NYMEM], double mv)
Definition at line 64 of file util.c.
References D, MINIMUM_DEPTH, and NXMEM.
Referenced by main().
void set_darray2d_zero (double ** arr, int NX, int NY)
Definition at line 4 of file util.c.
void set_darray3d_zero (double *** arr, int nz, int NX, int NY)
Definition at line 11 of file util.c.
Referenced by main(), read_tracer_init(), and step_fields().
void set_fix_darray2d_zero (double arr[NXMEM][NYMEM])
Definition at line 27 of file util.c.
References NXMEM.
Referenced by main(), and step_fields().
void set_fix_darray3d_zero (double arr[][NXMEM][NYMEM], int nz)
Definition at line 19 of file util.c.
References NXMEM.
Referenced by read_tracer_init(), and step_fields().